### ISSUE TITLE
Cannot create survey with indexing starts from 0

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#15]
new survey > When indexing is set to 0 > save 

current: Indexing is saved as '1'
Expected: should be able to save the indexing starts from 0

![indexing](https://user-images.githubusercontent.com/56568887/67656488-0b3ed580-f9a8-11e9-822d-66064e6ec64f.png)

**Comment by nayanie-envision** [comment]
If indexing set greater than 1, save without any issue

**Comment by Radhika-Envision** [comment]
fixed. it may input 0 and positive number, any other input should change to default value 1.
