### ISSUE TITLE
submeasure indexing issue

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#16]
screenshot attached

![indexing2](https://user-images.githubusercontent.com/56568887/67723577-98c60800-fa30-11e9-84ac-15dde226907c.png)

**Comment by nayanie-envision** [comment]
James (upmark) reported this:
![indexing J](https://user-images.githubusercontent.com/56568887/67724149-3968f780-fa32-11e9-95a1-52c59dee86e5.png)

**Comment by Radhika-Envision** [comment]
fix submeasure sequence number start from 2, now submeasure sequence number start from 1
