### ISSUE TITLE
Cannot see Measure weight / no of measures

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#21]
Logged in as admin  > select the survey measure > cannot see Weight and Number of measures 

![image](https://user-images.githubusercontent.com/56568887/68101793-8d3c7a80-ff23-11e9-821f-fe8b37c2f349.png)

**Comment by Radhika-Envision** [comment]
as measure list , every line is one measure, so display sub measure number of measure.

**Comment by nayanie-envision** [comment]
Previously Weight & Number of measures displayed.
As each line represents a measure, displaying Number of measure does not make any sense .
Instead, now displays Weight & Number of sub measures in that measure.
