### ISSUE TITLE
Error when creating measure

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#3]
Under   ' IAM Asset Management Survey (Test)'      There are 6 surveys display, but 5 locked ( not purchased)  
   
 Message displays:      '5 surveys have not been purchased.   You can't create submissions against those surveys. To gain access, contact   the survey manager.'     

Top of the page:     'A survey has an error'

Is this an existing error before the change? What is the reason behind this?.

FYI: When refresh the page, re-enter same details and submit  - error disappears and allowed to save.

**Comment by Radhika-Envision** [comment]
existing behavior

**Comment by nayanie-envision** [comment]
Seems this is an existing issue. Will not do further investigation / fixes at this stage.
