### ISSUE TITLE
Message is bit confusing ( related to 'link' )

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#33]
1)
1. created a measure without submeasure (M1)
2. created a measure with submeasures (M2)

create new measure > switch on sub measure > click on link button >  popup displays with list of all created measures (M1 & M2)
Select M1 from the list 
Then message displays - 'Submeasures in another measure should be more than the submeasure number of current measure' 

Message is bit confusing. Can we change the text to 'Selected measure should be having one or more sub measures'

**Comment by Radhika-Envision** [comment]
I change message as "Measure which selected response type used by should be having equal or more sub measures than the sub measure number of current measure"

**Comment by nayanie-envision** [comment]
Please change the message to :
'Could not link: Selected response type should be having equal or more sub measures than the current measure'

**Comment by Radhika-Envision** [comment]
message had changed
