### ISSUE TITLE
Behaviour verification

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#34]
Assume below behaviours are correct:
1. Copy  - displays only existing measures have no sub measures 
2. Link - displays measures wuth sub measures AND measures have no sub measures

**Comment by Radhika-Envision** [comment]
1. when in create or edit measure without sub measure, copy or link - displays only response type used by existing measures have no sub measures;

2. when in create or edit measure with sub measure, copy or link -  displays all response type
