### ISSUE TITLE
Grouping not appearing when clerk doing the survey

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#35]
Created a survey with grouping 
but when clerk logged in and doing the survey, cannot see grouping:

![image](https://user-images.githubusercontent.com/56568887/71512521-b4437700-28ea-11ea-9f23-dac6422395ef.png)

**Comment by Radhika-Envision** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/47763143/71565395-93ee0500-2b02-11ea-8d69-49f2ef98aaff.png)

It should see grouping when clerk logged in. Maybe caching cause.
