### ISSUE TITLE
Added survey not listed 

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#4]
Created survey not appears in the list.
But it is in the database. It appears when id is submitted in URL.

URL : http://52.237.232.78/#/3/program/0b588a80-afba-49cf-a52e-566e43f80ab0 

![Survey not appears in list](https://user-images.githubusercontent.com/56568887/66793093-84b9db00-ef47-11e9-8038-4e008f694268.png)

**Comment by Radhika-Envision** [comment]
maybe not list the other page in all programs page, when go to suitable page, should got the correct program and go to that program, the survey could be display.
