### ISSUE TITLE
Error when saving survey with category

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#5]
login as author (role)
Create program  > save
Click on '+'  button to Create new survey.
Provide survey name , description
In 'Hierarchy' section, click on '+' button to create new category
Provide category name , measures, indexing displayed as '1'
Click on 'Save' 

Error: 'Could not save: Structure is invalid: length of value must be at least 1 for dictionary value @ data['levels']['lable'].got'

Note:
The difference is survey not saved before adding the category. 
![create new survey](https://user-images.githubusercontent.com/56568887/66793451-2857bb00-ef49-11e9-880e-f4196af9f63d.png)

As adding categoty option is allowed before saving the survey, new survey with category should saved to the database.

**Comment by Radhika-Envision** [comment]
should input short label
