### ISSUE TITLE
All measures cannot see in one view

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#8]
According to the requirement, all measures should be listed in one view. Is this implemented?

please see attached requirement document.
![All measures in one view ](https://user-images.githubusercontent.com/56568887/66794936-c69a4f80-ef4e-11e9-84da-c55ad7548440.png)

**Comment by Radhika-Envision** [comment]
all measures in one parent node in one view

**Comment by nayanie-envision** [comment]
one view : category > all measures / sub measures
