### ISSUE TITLE
When scrolling, category info not stays on top

### ISSUE THREAD

**Issue by nayanie-envision** [Radhika-Envision/Upmark#9]
Login as an author & created a survey. 
Then login as clerk to do the survey.
When scrolling down, current category info panel not stick on top.

**Current behavior:**
![no info panel when scroll down](https://user-images.githubusercontent.com/56568887/66795350-16c5e180-ef50-11e9-89d2-d89619eb5578.png)

**Requirement:**
![category info](https://user-images.githubusercontent.com/56568887/66795382-2c3b0b80-ef50-11e9-98f4-2c747a11c331.png)

**Comment by Radhika-Envision** [comment]
add srcoll bar for measures display
